load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_test")

rust_test(
    name = "firma_e2e_test",
    srcs = glob(["tests/e2e/**/*.rs"]),
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
        package_name = "crates/firma",
    ),
    crate_name = "e2e",
    crate_root = "tests/e2e/main.rs",
    data = [
        "//crates/firma:firma",
    ] + glob(["tests/e2e/snapshots/**/*.snap"]),
    deps = all_crate_deps(normal = True, package_name = "crates/firma") + all_crate_deps(normal_dev = True, package_name = "crates/firma") + [
        "//crates/firma-sidecar:firma_sidecar",
    ],
    edition = crate_edition(package_name = "crates/firma"),
    proc_macro_deps = all_crate_deps(proc_macro = True, package_name = "crates/firma") + all_crate_deps(proc_macro_dev = True, package_name = "crates/firma"),
    rustc_env = {
        "CARGO_BIN_EXE_firma": "$(rootpath //crates/firma:firma)",
    },
)

exports_files([
    "Cargo.lock",
    "Cargo.toml",
])
