module(
    name = "openfirma",
    version = "0.1.2",
)

bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "rules_rust_prost", version = "0.71.3")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "protobuf", version = "33.4", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_proto", version = "7.1.0")

single_version_override(
    module_name = "rules_rust",
    patch_strip = 1,
    patches = ["//bazel:rules_rust-windows-ldep-consolidation.patch"],
    version = "0.71.3",
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    versions = ["1.96.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.render_config(
    generate_cargo_toml_env_vars = False,
)
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    lockfile = "//:Cargo.Bazel.lock",
    manifests = ["//:Cargo.toml"],
)
crate.spec(
    package = "protoc-gen-prost",
    repositories = ["prost_plugins"],
    version = "0.5.0",
)
crate.spec(
    package = "protoc-gen-tonic",
    repositories = ["prost_plugins"],
    version = "0.5.0",
)
crate.annotation(
    crate = "protoc-gen-prost",
    gen_binaries = ["protoc-gen-prost"],
    repositories = ["prost_plugins"],
)
crate.annotation(
    crate = "protoc-gen-tonic",
    gen_binaries = ["protoc-gen-tonic"],
    repositories = ["prost_plugins"],
)
crate.from_specs(
    name = "prost_plugins",
    cargo_lockfile = "//:Cargo.Prost.lock",
    lockfile = "//:Cargo.Prost.Bazel.lock",
)
use_repo(crate, "crates", "prost_plugins")

register_toolchains("//bazel/proto:prost_toolchain")
