load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_binary(
    name = "firma-vz-runner",
    crate = "firma_vz_runner",
    crate_root = "src/main.rs",
    edition = "2024",
    env = {
        "CARGO_PKG_VERSION": "0.1.2",
    },
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//third-party:anyhow",
        "//third-party:clap",
        "//third-party:objc2-virtualization",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:thiserror",
    ],
)
