load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "firma_core",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = ["firma.cedarschema"],
    crate_name = "firma_core",
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":firma_core",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
)

rust_doc_test(
    name = "doc_tests",
    crate = ":firma_core",
)

rust_doc(
    name = "docs",
    crate = ":firma_core",
)

exports_files(["Cargo.toml"])
