load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")

COMMON_ENV = {
    "CARGO_PKG_NAME": "firma-protobuf",
    "CARGO_PKG_VERSION": "0.2.0",
    "CARGO_PKG_VERSION_MAJOR": "0",
    "CARGO_PKG_VERSION_MINOR": "2",
    "CARGO_PKG_VERSION_PATCH": "0",
    "CARGO_PKG_VERSION_PRE": "",
}

PROTO_SRCS = glob(["proto/**/*.proto"])

genrule(
    name = "firma-protobuf-manifest-dir",
    srcs = PROTO_SRCS,
    out = "manifest_dir",
    cmd = "mkdir -p $OUT/proto/firma/v1 && cp $SRCS $OUT/proto/firma/v1/",
)

cargo.rust_library(
    name = "firma_protobuf",
    crate = "firma_protobuf",
    crate_root = "src/lib.rs",
    edition = "2024",
    srcs = glob(["src/**/*.rs"]) + PROTO_SRCS,
    env = COMMON_ENV | {
        "OUT_DIR": "$(location :firma-protobuf-build-script-run[out_dir])",
    },
    rustc_flags = ["@$(location :firma-protobuf-build-script-run[rustc_flags])"],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party:prost",
        "//third-party:prost-types",
        "//third-party:tonic",
        "//third-party:tonic-prost",
    ],
)

cargo.rust_binary(
    name = "firma-protobuf-build-script-build",
    crate = "build_script_build",
    crate_root = "build.rs",
    edition = "2024",
    srcs = ["build.rs"] + PROTO_SRCS,
    env = COMMON_ENV,
    visibility = [],
    deps = ["//third-party:tonic-prost-build"],
)

buildscript_run(
    name = "firma-protobuf-build-script-run",
    package_name = "firma-protobuf",
    buildscript_rule = ":firma-protobuf-build-script-build",
    env = COMMON_ENV,
    manifest_dir = ":firma-protobuf-manifest-dir",
    version = "0.2.0",
)
