load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_library(
    name = "firma_stack",
    crate = "firma_stack",
    crate_root = "src/lib.rs",
    edition = "2024",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["PUBLIC"],
    deps = [
        "//crates/firma-config-loader:firma_config_loader",
        "//crates/firma-runtime-state:firma_runtime_state",
        "//third-party:ctrlc",
        "//third-party:serde",
        "//third-party:thiserror",
        "//third-party:toml",
        "//third-party:tracing",
    ] + select({
        "prelude//os/constraints:windows": ["//third-party:windows-sys"],
        "DEFAULT": ["//third-party:nix"],
    }),
)
