load("@prelude//:prelude.bzl", "native")
load("@prelude//rust:cargo_package.bzl", "cargo")

cargo.rust_binary(
    name = "firma",
    crate = "firma",
    crate_root = "src/main.rs",
    edition = "2024",
    env = {
        "CARGO_PKG_VERSION": "0.1.2",
    },
    srcs = glob([
        "src/**/*.rs",
        "templates/**/*",
    ]),
    deps = [
        "//crates/firma-authority:firma_authority",
        "//crates/firma-config-loader:firma_config_loader_clap",
        "//crates/firma-core:firma_core",
        "//crates/firma-run:firma_run",
        "//crates/firma-runtime-state:firma_runtime_state",
        "//crates/firma-sidecar:firma_sidecar",
        "//crates/firma-stack:firma_stack",
        "//third-party:anyhow",
        "//third-party:cedar-policy",
        "//third-party:chrono",
        "//third-party:clap",
        "//third-party:ctrlc",
        "//third-party:dialoguer",
        "//third-party:miette",
        "//third-party:nix",
        "//third-party:owo-colors",
        "//third-party:p256",
        "//third-party:pasetors",
        "//third-party:rcgen",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:serde_yaml",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:textwrap",
        "//third-party:thiserror",
        "//third-party:time",
        "//third-party:tokio",
        "//third-party:tokio-util",
        "//third-party:toml",
        "//third-party:toml_edit",
        "//third-party:tracing",
        "//third-party:tracing-subscriber",
        "//third-party:uuid",
        "//third-party:x509-parser",
    ],
)

native.rust_test(
    name = "cli_help_test",
    crate = "cli_help",
    crate_root = "tests/cli_help.rs",
    edition = "2024",
    env = {
        "CARGO_BIN_EXE_firma": "$(location :firma)",
    },
    srcs = ["tests/cli_help.rs"],
    deps = [],
)

native.rust_test(
    name = "cli_parsing_test",
    crate = "cli_parsing",
    crate_root = "tests/cli_parsing.rs",
    edition = "2024",
    env = {
        "CARGO_BIN_EXE_firma": "$(location :firma)",
    },
    srcs = ["tests/cli_parsing.rs"],
    deps = [
        "//crates/firma-config-loader:firma_config_loader",
        "//third-party:clap",
    ],
)

native.rust_test(
    name = "run_authority_flags_test",
    crate = "run_authority_flags",
    crate_root = "tests/run_authority_flags.rs",
    edition = "2024",
    env = {
        "CARGO_BIN_EXE_firma": "$(location :firma)",
    },
    srcs = ["tests/run_authority_flags.rs"],
    deps = [],
)

native.rust_test(
    name = "run_autostart_flags_test",
    crate = "run_autostart_flags",
    crate_root = "tests/run_autostart_flags.rs",
    edition = "2024",
    env = {
        "CARGO_BIN_EXE_firma": "$(location :firma)",
    },
    srcs = ["tests/run_autostart_flags.rs"],
    deps = [],
)
