load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "firma",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = glob(["templates/**"]),
    crate_name = "firma",
    crate_root = "src/main.rs",
    deps = all_crate_deps(normal = True) + [
        "//crates/firma-authority:firma_authority",
        "//crates/firma-config-loader:firma_config_loader",
        "//crates/firma-core:firma_core",
        "//crates/firma-run:firma_run",
        "//crates/firma-runtime-state:firma_runtime_state",
        "//crates/firma-sidecar:firma_sidecar",
        "//crates/firma-stack:firma_stack",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    version = "0.1.2",
)

exports_files(["Cargo.toml"])
