# @generated by `cargo buckal`

load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")

def system_demo_cxx_toolchain():
    # We override the demo toolchains so we can avoid forcing `-fuse-ld=lld`.
    # The bundled demo cxx toolchain uses clang++ and adds `-fuse-ld=lld` on Linux,
    # but some environments don't have lld installed.
    system_cxx_toolchain(
        name = "cxx",
        compiler = select({
            "prelude//os/constraints:linux": "/usr/bin/gcc",
            "prelude//os/constraints:macos": "/usr/bin/clang",
            "prelude//os/constraints:windows": "cl.exe",
            "DEFAULT": "/usr/bin/cc",
        }),
        # Keep `g++` as the C++ compiler on Linux so the prelude doesn't inject
        # `-fuse-ld=lld` (lld isn't guaranteed to exist). Other OSes use their
        # native compilers.
        cxx_compiler = select({
            "prelude//os/constraints:linux": "/usr/bin/g++",
            "prelude//os/constraints:macos": "/usr/bin/clang++",
            "prelude//os/constraints:windows": "cl.exe",
            "DEFAULT": "/usr/bin/c++",
        }),
        linker = select({
            "prelude//os/constraints:linux": "/usr/bin/g++",
            "prelude//os/constraints:macos": "/usr/bin/clang++",
            "prelude//os/constraints:windows": "link.exe",
            "DEFAULT": "/usr/bin/c++",
        }),
        archiver = select({
            "prelude//os/constraints:linux": "/usr/bin/ar",
            "prelude//os/constraints:macos": "/usr/bin/ar",
            "prelude//os/constraints:windows": "lib.exe",
            "DEFAULT": "/usr/bin/ar",
        }),
        # Buck prelude's system C++ toolchain injects `-fuse-ld=lld` into the
        # linker wrapper. Some environments don't ship `ld.lld`,
        # so append `-fuse-ld=bfd` to override it for Linux targets.
        link_flags = select({
            "prelude//os/constraints:linux": ["-fuse-ld=bfd"],
            "DEFAULT": [],
        }),
        visibility = ["PUBLIC"],
    )
