load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "firma_demo_fixture",
    srcs = ["src/lib.rs"],
    aliases = aliases(),
    crate_name = "firma_demo_fixture",
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_binary(
    name = "firma-demo-fixture",
    srcs = ["src/bin/server.rs"],
    aliases = aliases(),
    crate_name = "firma_demo_fixture_server",
    deps = all_crate_deps(normal = True) + [":firma_demo_fixture"],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_binary(
    name = "firma-demo-fixture-client",
    srcs = ["src/bin/client.rs"],
    aliases = aliases(),
    crate_name = "firma_demo_fixture_client",
    deps = all_crate_deps(normal = True) + [":firma_demo_fixture"],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "client_unit_tests",
    srcs = ["src/bin/client.rs"],
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "firma_demo_fixture_client_test",
    deps = all_crate_deps(normal = True) + all_crate_deps(normal_dev = True) + [
        ":firma_demo_fixture",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True) + all_crate_deps(proc_macro_dev = True),
)

rust_doc_test(
    name = "doc_tests",
    crate = ":firma_demo_fixture",
)

exports_files(["Cargo.toml"])
