load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "firma_authority",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_name = "firma_authority",
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True) + [
        "//crates/firma-config-loader:firma_config_loader",
        "//crates/firma-core:firma_core",
        "//crates/firma-protobuf:firma_protobuf",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "unit_tests",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":firma_authority",
    deps = all_crate_deps(normal_dev = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "profile_developer_integration_test",
    srcs = ["tests/profile_developer.rs"],
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "profile_developer_integration_test",
    deps = all_crate_deps(normal = True) + all_crate_deps(normal_dev = True) + [":firma_authority"],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True) + all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "e2e_integration_test",
    srcs = ["tests/e2e.rs"],
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "authority_e2e_integration_test",
    deps = all_crate_deps(normal = True) + all_crate_deps(normal_dev = True) + [
        ":firma_authority",
        "//crates/firma-core:firma_core",
        "//crates/firma-protobuf:firma_protobuf",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True) + all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "e2e_mtls_integration_test",
    srcs = ["tests/e2e_mtls.rs"],
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "authority_e2e_mtls_integration_test",
    deps = all_crate_deps(normal = True) + all_crate_deps(normal_dev = True) + [
        ":firma_authority",
        "//crates/firma-protobuf:firma_protobuf",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True) + all_crate_deps(proc_macro_dev = True),
)

rust_doc_test(
    name = "doc_tests",
    crate = ":firma_authority",
)

exports_files(["Cargo.toml"])
