load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_files")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")

package(default_visibility = ["//visibility:public"])

pkg_files(
    name = "firma_unix_files",
    srcs = ["//crates/firma:firma"],
    attributes = pkg_attributes(mode = "0555"),
    renames = {
        "//crates/firma:firma": "firma",
    },
)

pkg_tar(
    name = "firma_unix_archive",
    srcs = [":firma_unix_files"],
    extension = "tar.gz",
    out = "firma.tar.gz",
)

pkg_files(
    name = "firma_windows_files",
    srcs = ["//crates/firma:firma"],
    renames = {
        "//crates/firma:firma": "firma.exe",
    },
)

pkg_zip(
    name = "firma_windows_archive",
    srcs = [":firma_windows_files"],
    out = "firma.zip",
)
