['cfg(windows)']
features = [
  "basetsd",
  "cfg",
  "cfgmgr32",
  "combaseapi",
  "devpropdef",
  "excpt",
  "fileapi",
  "guiddef",
  "ktmtypes",
  "libloaderapi",
  "limits",
  "minwinbase",
  "minwindef",
  "ntdef",
  "ntstatus",
  "oaidl",
  "objidl",
  "objidlbase",
  "processthreadsapi",
  "propidl",
  "reason",
  "rpc",
  "rpcdce",
  "rpcndr",
  "shtypes",
  "unknwnbase",
  "vadefs",
  "vcruntime",
  "windef",
  "wingdi",
  "wincontypes",
  "winnt",
  "winreg",
  "wtypes",
  "wtypesbase",
]
