load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "firma_sidecar",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_name = "firma_sidecar",
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True) + [
        "//crates/firma-core:firma_core",
        "//crates/firma-grpc-interceptor-proto:firma_grpc_interceptor_proto",
        "//crates/firma-protobuf:firma_protobuf",
        "//crates/firma-runtime-state:firma_runtime_state",
    ],
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "unit_tests",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":firma_sidecar",
    data = glob(["config/mappings/*.toml"]),
    deps = all_crate_deps(normal_dev = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    rustc_env = {
        "CARGO_MANIFEST_DIR": "crates/firma-sidecar",
    },
)

rust_doc_test(
    name = "doc_tests",
    crate = ":firma_sidecar",
)

exports_files(["Cargo.toml"])
