load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "firma_config_loader",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_features = [
        "clap",
        "test-utils",
    ],
    crate_name = "firma_config_loader",
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

exports_files(["Cargo.toml"])
